// Auto-generated by translations:generate. Do not edit.
import 'i18next';

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    resources: {
      'common': typeof import('./it/common.json');
    };
  }
}
