name: Phpstan

on:
  push:
    branches: [staging]
    paths:
      - "**/*.php"
      - "composer.json"
      - "composer.lock"
      - "phpstan.neon*"
      - ".github/workflows/phpstan.yml"
  pull_request:
    paths:
      - "**/*.php"
      - "composer.json"
      - "composer.lock"
      - "phpstan.neon*"
      - ".github/workflows/phpstan.yml"

jobs:
  phpstan:
    uses: Scrapkit/ci-pipeline/.github/workflows/phpstan.yml@v1
    with:
      php-version: "8.4"
