name: Prettier

on:
  push:
    branches: [main]
    paths:
      - "resources/**"
      - "prettier.config.js"
      - ".prettierignore"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/prettier.yml"
  pull_request:

jobs:
  prettier-check:
    uses: Scrapkit/ci-pipeline/.github/workflows/prettier-check.yml@v1
    with:
      node-version: "22"
